### ISSUE TITLE
Failed to activate the clearnight-retro-ui package

### ISSUE THREAD

**Issue by ronnyvv** [ClearNight/clearnight-retro-ui#2]
Happened when selecting the theme the first time after install

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: "Fedora release
**Thrown From**: [clearnight-retro-ui](https://github.com/ClearNight/clearnight-retro-ui) package 1.0.1

### Stack Trace

Failed to activate the clearnight-retro-ui package

```
At Cannot read property 'toLowerCase' of undefined

TypeError: Cannot read property 'toLowerCase' of undefined
    at setLayoutMode (/packages/clearnight-retro-ui/lib/main.coffee:27:66)
    at /packages/clearnight-retro-ui/lib/main.coffee:9:7
    at Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:1056:11)
    at Config.observe (/usr/share/atom/resources/app/src/config.js:485:25)
    at Object.activate (/packages/clearnight-retro-ui/lib/main.coffee:8:17)
    at ThemePackage.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/theme-package.js:50:24)
    at ThemePackage.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/theme-package.js:47:20)
    at Promise (<anonymous>)
    at ThemePackage.activate (/usr/share/atom/resources/app/src/theme-package.js:44:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at deactivateThemes.then (/usr/share/atom/resources/app/src/theme-manager.js:335:55)
    at <anonymous>
```

### Commands

```
     -8:03.3.0 core:close (div.package-detail.panels-item)
     -2:05.1.0 settings-view:open (input.hidden-input)
     -1:58.1.0 core:confirm (input.hidden-input)
     -1:56.8.0 core:select-all (input.hidden-input)
     -1:55.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-ide-debugger-node 0.7.1 
atom-ide-ui 0.11.2 
atom-maven 1.3.2 
autocomplete-modules 2.0.0 
clearnight-retro-ui 1.0.1 
duotone-light-syntax 2.1.0 
editorconfig 2.2.2 
file-icons 2.1.20 
fonts 3.0.3 
git-blame 1.6.0 
git-time-machine 2.0.1 
gl-light-syntax 3.0.0 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-flowtype 0.23.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-ruby 0.1.10 
ide-typescript 0.7.6 
ide-yaml 0.4.3 
js-refactor-atom 0.10.1 
language-babel 2.85.0 
language-ejs 0.4.0 
language-groovy 0.7.0 
linter 2.2.0 
linter-eslint 8.4.1 
min-ui 0.0.4 
pigments 0.40.2 
prettier-atom 0.53.0 
project-manager 3.3.5 
project-sidebar 1.3.0 
split-diff 1.5.2 
sync-settings 0.8.6 
teletype 0.13.2 
wordcount 2.10.4 
zentabs 0.8.9 
```

**Comment by thornjad** [comment]
Sorry it took me a bit to get back to this. In the package settings, what is your layout mode set to? Should be either 'auto', 'compact' or 'spacious'.

**Comment by mslw** [comment]
I have the same error when launching Atom (the UI theme seems to work though). My layout is set to Auto. Changing it takes no effect.

**Comment by leavengood** [comment]
The code is using the wrong namespace for the settings, it should be using `clearnight-retro-ui` but uses `clear-night-ui`:

https://github.com/ClearNight/clearnight-retro-ui/blob/master/lib/main.coffee#L8

Since this setting doesn't exist, `undefined` is passed into `setLayoutMode`, which of course doesn't have a toLowerCase() method.

The fix is simple enough that I'm not going to bother with a PR, but the spec also needs to be changed.

Nice theme besides this minor bug!

**Comment by leavengood** [comment]
The package name also needs to be fixed in settings.less so that the SVG dropdown images can be found:

https://github.com/ClearNight/clearnight-retro-ui/blob/master/styles/settings.less#L503

And line 506.

I guess the name of this had to be changed when you published it?

**Comment by thornjad** [comment]
@leavengood you found it! The core of this theme is taken from [Clear Night UI](https://github.com/clearnight/clear-night-ui), and I obviously missed a couple changes. Thank you! An update will be out momentarily.

**Comment by leavengood** [comment]
OK, it all is starting to make sense! I'm glad I could be helpful.
